### ISSUE TITLE
Mesh output does not work in Mathematica 12

### ISSUE THREAD

**Issue by pruvisto** [xslittlegrass/POVRayRender-For-Mathematica#2]
As far as I can tell, `POVRayRender` always produces an empty mesh in Mathematica 12. For instance, the example
```
POVRayRender@Plot3D[Sin[x + y^2], {x, -3, 3}, {y, -2, 2}, ColorFunction -> Hue, Mesh -> None, PlotPoints -> 50]
```
from the readme produces the following error:
```
Parse Error: No vertices in triangle mesh.
```
Calling `POVRayRender` with `Method -> "Triangle"` works, but produces a completely white plot, so it seems that all the colour information is ignored.

**Comment by HyperGroups** [comment]
Same Problem,
Tested @12.1 on Windows and POV 3.7
Works well on 11.3 on Windows and POV 3.7

**Comment by SqRoots** [comment]
> As far as I can tell, `POVRayRender` always produces an empty mesh in Mathematica 12. For instance, the example
> 
> ```
> POVRayRender@Plot3D[Sin[x + y^2], {x, -3, 3}, {y, -2, 2}, ColorFunction -> Hue, Mesh -> None, PlotPoints -> 50]
> ```
> 
> from the readme produces the following error:
> 
> ```
> Parse Error: No vertices in triangle mesh.
> ```
> 
> Calling `POVRayRender` with `Method -> "Triangle"` works, but produces a completely white plot, so it seems that all the colour information is ignored.


Bug #2 is due to the upgrade of the function "Cases" in Mathematica 12.x.x.
It should be `gc=First@Cases[p,_GraphicsComplex,Infinity];` in function `generatePovrayStringUsingMesh`.
I have submitted a pull request to the ower.
